# Generated by Django 3.0.4 on 2020-03-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('category_descp', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='geo_cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=150)),
                ('lat', models.CharField(max_length=150)),
                ('lng', models.CharField(max_length=1500)),
                ('addr1', models.CharField(max_length=350)),
                ('addr2', models.CharField(max_length=350)),
                ('addr3', models.CharField(max_length=350)),
                ('addr4', models.CharField(max_length=350)),
                ('pin', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='local_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_name', models.CharField(max_length=150)),
                ('info_descp', models.CharField(max_length=1500)),
                ('geo_cache_id', models.IntegerField()),
                ('sub_category_id', models.IntegerField()),
                ('lat', models.CharField(max_length=150)),
                ('lng', models.CharField(max_length=150)),
                ('addr', models.CharField(max_length=1500)),
                ('pin', models.CharField(max_length=150)),
                ('key_words', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=150)),
                ('category_master_id', models.IntegerField()),
                ('sub_descp', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('addr', models.CharField(max_length=1500)),
                ('pin', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=50)),
                ('dt', models.CharField(max_length=150)),
                ('tm', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
