# Generated by Django 3.0.4 on 2020-03-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_master_geo_cache_local_info_sub_category_master_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='route_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=150)),
                ('st_lat', models.CharField(max_length=150)),
                ('st_lng', models.CharField(max_length=150)),
                ('end_name', models.CharField(max_length=150)),
                ('end_lat', models.CharField(max_length=150)),
                ('end_lng', models.CharField(max_length=150)),
                ('route_descp', models.CharField(max_length=1500)),
                ('dt', models.CharField(max_length=150)),
                ('tm', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user_query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('st_name', models.CharField(max_length=150)),
                ('end_name', models.CharField(max_length=150)),
                ('query', models.CharField(max_length=1500)),
                ('dt', models.CharField(max_length=150)),
                ('tm', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
