# Generated by Django 3.0.5 on 2020-04-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_route_info_user_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='route_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField()),
                ('loc_id', models.IntegerField()),
            ],
        ),
    ]
