# Generated by Django 3.0.5 on 2020-04-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_route_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
